const students = [
    {   
        roll             : 1,
        name             : `Ananda Saha`,
        bangla           : 50,
        english          : 71,
        math             : 80,
        socialScience    : 83,
        science          : 73,
        religion         : 60,
    },
    {   
        roll             : 2,
        name             : `Akash`,
        bangla           : 62,
        english          : 71,
        math             : 80,
        socialScience    : 83,
        science          : 73,
        religion         : 60,
    },
    {   
        roll             : 3,
        name             : `Sayed`,
        bangla           : 55,
        english          : 71,
        math             : 80,
        socialScience    : 73,
        science          : 73,
        religion         : 60,
    },
    {   
        roll             : 4,
        name             : `Amin`,
        bangla           : 54,
        english          : 71,
        math             : 40,
        socialScience    : 83,
        science          : 73,
        religion         : 60,
    },
    {   
        roll             : 5,
        name             : `Nayon`,
        bangla           : 53,
        english          : 71,
        math             : 80,
        socialScience    : 83,
        science          : 53,
        religion         : 60,
    },
    {   
        roll             : 6,
        name             : `samrat`,
        bangla           : 52,
        english          : 71,
        math             : 80,
        socialScience    : 93,
        science          : 73,
        religion         : 50,
    },
    {   
        roll             : 7,
        name             : `Alam`,
        bangla           : 60,
        english          : 71,
        math             : 77,
        socialScience    : 80,
        science          : 73,
        religion         : 60,
    },
    {   
        roll             : 8,
        name             : `seykat`,
        bangla           : 57,
        english          : 71,
        math             : 80,
        socialScience    : 73,
        science          : 73,
        religion         : 60,
    },
    {   
        roll             : 9,
        name             : `Ismail`,
        bangla           : 51,
        english          : 71,
        math             : 70,
        socialScience    : 83,
        science          : 53,
        religion         : 60,
    },
    
];