// - Create data in a student array and object  where there will be data of about 50 people and print data of Mirpur and Banani residents starting from there


const studentArray = [
    {
       roll         : 01,
       name         : `Ananda`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Mirpur`,
    },
    {
       roll         : 02,
       name         : `Abusyde`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Banani`,
    },
    {
       roll         : 03,
       name         : `Hasnath`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Uttara`,
    },
    {
       roll         : 04,
       name         : `Hasan`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Badda`,
    },
    {
       roll         : 05,
       name         : `Nando`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Uttara`,
    },
    {
       roll         : 06,
       name         : `Pranto`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Mirpur`,
    },
    {
       roll         : 07,
       name         : `Partho`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Badda`,
    },
    {
       roll         : 08,
       name         : `Jibon`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Uttara`,
    },
    {
       roll         : 09,
       name         : `Ikbal`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Badda`,
    },
    {
       roll         : 10,
       name         : `Jabad`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Banani`,
    },
    {
       roll         : 11,
       name         : `kamal`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Mirpur`,
    },
    {
       roll         : 12,
       name         : `Rohim`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Uttara`,
    },
    {
       roll         : 13,
       name         : `Korim`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Badda`,
    },
    {
       roll         : 14,
       name         : `Sujan`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Mirpur`,
    },
    {
       roll         : 15,
       name         : `Jabbr`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Uttara`,
    },
    {
       roll         : 16,
       name         : `Rabya`,
       class        : `Four`,
       gender       : `Female`,
       location     : `Badda`,
    },
    {
       roll         : 17,
       name         : `Jahid`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Banani`,
    },
    {
       roll         : 18,
       name         : `Sharmin`,
       class        : `Four`,
       gender       : `Female`,
       location     : `Uttara`,
    },
    {
       roll         : 20,
       name         : `Sanjoy`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Banani`,
    },
    {
       roll         : 21,
       name         : `Akash`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Badda`,
    },
    {
       roll         : 22,
       name         : `Pejush`,
       class        : `Five`,
       gender       : `Male`,
       location     : `Uttara`,
    },
    {
       roll         : 23,
       name         : `Juyal`,
       class        : `Four`,
       gender       : `Male`,
       location     : `Badda`,
    },
    {
       roll         : 24,
       name         : `Moumita`,
       class        : `Five`,
       gender       : `Female`,
       location     : `Mirpur`,
    },
    {
       roll         : 25,
       name         : `Rupa`,
       class        : `Four`,
       gender       : `Female`,
       location     : `Banani`,
    },

];


